### ISSUE TITLE
Create a Beta Docker incl. Avahi

### ISSUE THREAD

**Issue by bjoerns1983** [ampache/ampache-docker#1]
Hi there,
dockerizing Ampache is a great idea.
I would like to ask if it is possible to create a docker of the current Ampache beta incl. Avahi and the suitable Avahi config. So it would be possible to use Ampache as daapd server.

**Comment by Afterster** [comment]
Looks like a good idea, I believe all other backend should also be an option on docker package installation. I will update this once https://github.com/ampache/ampache/issues/718 handled and when I get some times (still looking for a maintainer for ampache-docker, and ampache-debian too btw, so I can focus myself on Ampache core).

**Comment by idelsink** [comment]
@Afterster If you're interested I made a version of ampache-docker that uses Alpine linux. It can also compose ampache from a given git hash. https://github.com/idelsink/ampache-docker
