### ISSUE TITLE
Docker Newb Question, How to use this image for another port?

### ISSUE THREAD

**Issue by qwertyuser1983** [ampache/ampache-docker#10]
Dear Ampache,

In my server, port 80 is taken, so I change the script to 

docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 81:81 ampache/ampache. 

It installed, but running http://127.0.0.1:81 produce nothing. :(

Need a clue on how to use another ports, please. :)

**Comment by jodumont** [comment]
try something like
docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 81:80 ampache/ampache
which means redirecting the docker-image port 80 on your host port 81

but for better usage you must plan a reverse proxy such as haproxy or nginx

**Comment by qwertyuser1983** [comment]
I tried this, and works. Thanks Jodumont. :)

docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 81:80 ampache/ampache
