### ISSUE TITLE
Web browser not playing songs when using non-standard port

### ISSUE THREAD

**Issue by MathijsNL** [ampache/ampache-docker#103]
Using the latest develop build, having a non-standard port prevents playing any songs. It looks like the ports get appended twice in each URL.

```
http://192.168.3.228:8084:8084/play/index.php?ssid=3c83583e2d640ad34a0fb7af408e204e&type=song&oid=1&uid=1&name=Rick%20Astley%20-%20Never%20Gonna%20Give%20You%20Up.mp3
```

Therefor no working music.

Changing the port back to port 80 makes it work again.

**Comment by lachlan-00** [comment]
what do you have for http_port, local_web_path, web_path and fallback_url?

Must be something wrong in the logic of `src/Module/Playback/Stream.php` in the get_base_url function

**Comment by KaeTuuN** [comment]
@MathijsNL 
What Version do you use?
Do you use a proxy like Nginx Proxy Manager in front?

I had the the same struggle after Migrating from a local nginx Instance to the Docker version behind NPM. In my case the `http_port` and the `local_web_path` variables had to be explicitly set in the config. In your case these should look like the this in the config:
```
http_port = 8084
local_web_path = http://192.168.3.228
```

**Comment by MathijsNL** [comment]
I actually fixed it by putting it behind a proxy. So now everything runs on localhost / port 80 and it works. Probably  better to do it that way anyway.

And I think it seems to be fixed now:

[Ampache 6.0.1](https://github.com/ampache/ampache/blob/develop/docs/CHANGELOG.md#ampache-601)
[Fixed](https://github.com/ampache/ampache/blob/develop/docs/CHANGELOG.md#fixed-3)
Check for duplicate ports in stream URL's
