### ISSUE TITLE
Ampache is forcing HTTP Url's

### ISSUE THREAD

**Issue by elohmeier** [ampache/ampache-docker#11]
Hello, I'm using this docker image with an SSL Reverse proxy in front of it.
I'm getting a lot of mixed-content errors, because ampache thinks it's running on port 80.

My setup is:
https://media.example.com -> http://192.168.1.2:5678 (maps to ampache-docker port 80).

Ampache actually get's the correct domain but not the correct protocol, so all URLs are like this: e.g. http://media.example.com/templates/base.css

**Comment by loripino21** [comment]
+1!!!

**Comment by max-k** [comment]
Hi, Any news on this ?

**Comment by elohmeier** [comment]
I'm not using it currently – don't know if any progress has been made on this issue.

**Comment by lachlan-00** [comment]
you can force https in the config
![image](https://user-images.githubusercontent.com/1305249/62844627-df477880-bd05-11e9-9bb8-54a1d5236b07.png)
