### ISSUE TITLE
6.1.0 Docker Images

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache-docker#110]
Not to be pushy, but will there be 6.1.0 docker images soon?  I've been staring at this for a few days now:

![image](https://github.com/ampache/ampache-docker/assets/8419000/c03ddba1-74d4-45d4-8253-f8caf3434c9d)

But no joy on "docker-compose pull"

**Comment by lachlan-00** [comment]
they should have been, i'll just check. i did a build all but didn't look whether it completed

**Comment by lachlan-00** [comment]
![image](https://github.com/ampache/ampache-docker/assets/1305249/abec3acc-19a6-4dce-b973-38ef26b4c22f)
might wanna use the right builder....
