### ISSUE TITLE
Config file outdated - ampache 6.x.x ships config_version 62 

### ISSUE THREAD

**Issue by choffm** [ampache/ampache-docker#117]
Hello,

I observed that the most recent `ampache/ampache` image with tag `6.3.1` (`latest`) always gives me warnings about outdated `ampache.cfg.php`. Updating the configuration via the UI doesn't throw an error, but doesn't resolve the problem.

So I checked the image and in `/var/tmp/ampache.cfg.php.dist`, the version is `62` indeed - although ampache `6.3.1` ships version `69`.

The reason for shipping a config file not matching with the ampache version is that in [Dockerfile#L79](https://github.com/ampache/ampache-docker/blob/master/Dockerfile#L79), `ampache.cfg.php.dist` is copied to `/var/tmp` from a 2 year old `ampache.cfg.php.dist` shipped in [this repository](https://github.com/ampache/ampache-docker/blob/master/data/config/ampache.cfg.php.dist). 

Is there a specific reason that we do not copy the config version shipped with the ampache release instead? As we download the release zip file that contains the config file with the correct version, we could copy it from there instead.

Regards
Clemens

**Comment by lachlan-00** [comment]
very out of date, updating the build now.

As for why i have no idea, i'll update that process to do something else later

**Comment by choffm** [comment]
I opened a pull-request for a long term fix.

**Comment by lachlan-00** [comment]
looks good for the builds i'll put it up the other branches now
