### ISSUE TITLE
Update please T T

### ISSUE THREAD

**Issue by qwertyuser1983** [ampache/ampache-docker#15]
Time to update to 3.8.3? :)

**Comment by idelsink** [comment]
If you want, I have a version that is already up to date with the latests release, see <https://hub.docker.com/r/idelsink/ampache/>

**Comment by qwertyuser1983** [comment]
Then, I shall try Your tonight, Idelsink :)

**Comment by qwertyuser1983** [comment]
Then, I shall try Your tonight, Idelsink :)

**Comment by idelsink** [comment]
Yes, that's right

**Comment by lachlan-00** [comment]
updated today.
