### ISSUE TITLE
How to get it working

### ISSUE THREAD

**Issue by xordspar0** [ampache/ampache-docker#17]
I had to make a couple changes to make this work for me.

1. Docker already untars files added with `ADD`, so a `cp` command is needed on line 28, not `tar`.
2. Installing with composer failed because maennchen/zipstream-php v0.4.1 requires php >= 5.6. Since no version of Ubuntu ships with php 5.6, I used the [release version](https://github.com/ampache/ampache/releases) of Ampache instead of master, which includes all the dependencies.

**Comment by idelsink** [comment]
You can check out my implementation of a ampache docker container: <https://hub.docker.com/r/idelsink/ampache/>
This also uses composer on a very lightweight alpine linux distro

**Comment by xordspar0** [comment]
Nice work on that one, @idelsink. Thanks for pointing that out to me.

**Comment by lachlan-00** [comment]
updated the official build today, have a look and let me know if anything is needed.
