### ISSUE TITLE
Get persistance of config folders.

### ISSUE THREAD

**Issue by antipiot** [ampache/ampache-docker#19]
It would be nice to be able to mount config and database folders to have persistance for the docker installation: as https://hub.docker.com/r/producerism/ampache-docker/

this is great to have an docker installation for newbies like me!

**Comment by lachlan-00** [comment]
can you test these changes?
https://github.com/ampache/ampache-docker/pull/26

If you put your config file in the docker folder it should copy them over on run.

**Comment by kuzi-moto** [comment]
@antipiot were you able to test the changes? Either way, if you use a bind mount or a named volume then the data will persist beyond the life of the container.

**Comment by lachlan-00** [comment]
plenty of options for persistence now
