### ISSUE TITLE
Plex is out of date - not working

### ISSUE THREAD

**Issue by lockntross** [ampache/ampache-docker#23]
Plex connected and as soon as you try and access the Ampache share -- you're greeted with this:
`Update your Plex Media Server
The server "Ampache-Music" is out of date and cannot be selected. This version of the web app requires Plex Media Server 1.3.0 or higher. Use one of the links below to open an available, out of date server directly.
Ampache-Music (Unavailable)`

**Comment by lachlan-00** [comment]
Closing. Plex is going to be removed in the next version of ampache
