### ISSUE TITLE
docker hub organisation

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache-docker#27]
@arielelkin are you the owner of the ampache docker org?

I either need the webhooks updated to allow new builds or access to the docker org

**Comment by arielelkin** [comment]
if you mean https://hub.docker.com/u/ampache, then no. 

@Afterster any ideas?

**Comment by lachlan-00** [comment]
@vollmerk and @wagnered I'm not sure who owns all the extra accounts here but this has made the official repo useless

**Comment by wagnered** [comment]
> I'm not sure who owns all the extra accounts here but this has made the official repo useless.

I haven't been following this repo. What has made the official repo useless?  By "extra accounts" do you mean contributers?  I'm more confused by this than you.  

-------- Original message --------
Subject: Re: [ampache/ampache-docker] docker hub organisation (#27)

**Comment by lachlan-00** [comment]
You know whats funny is when i made my own docker hub account and configured the webhooks the unofficial docker started building again.

No idea how but its un-useless again

**Comment by lachlan-00** [comment]
I think @Afterster must be the owner of the docker organisation due to the dates of the repo and the org creation date.

can you add me into the org so i can fix things up there? i need to start pushing builds for arm and allow the develop tage to be reachable instead of from my personal account.
https://hub.docker.com/u/ampache

**Comment by Afterster** [comment]
@lachlan-00 you are now an owner of ampache organization on Docker hub.
Sorry for the delay, I didn't saw the first highlight... Let me know if you need additional permission that I own.

**Comment by lachlan-00** [comment]
For docker no. I just pushed a multi-arch image to latest. :)

 For Ampache I want to pull in a few repos to the official org and I think you are the only owner of that org active.

I'll talk to you separately.
