### ISSUE TITLE
Error: Your config file is out of date! 

### ISSUE THREAD

**Issue by polhaghverdian** [ampache/ampache-docker#31]
Hi,

Latest Ampache docker from: dockerhub, i get below message

> Update available (4.0.3).
> See changes or download.
> 
> Error: Your config file is out of date!
> Generate and download new config file | Write new config file to disk

https://hub.docker.com/r/ampache/ampache

**Comment by lachlan-00** [comment]
write new config file is all you should need.

When 4 has stabilised a bit more i'll be updating the source conf file.
