### ISSUE TITLE
docker image still not up to date

### ISSUE THREAD

**Issue by TimoHocker** [ampache/ampache-docker#32]
There was a lot of activity on the ampache/ampache repo recently, but the only update on the docker image happened after 3a5e01b6c14ada9381d0597b4626c65c2160a961 on the ampache-docker repository
now the docker image is 4.0.3 while it could already be on 4.0.4

there either has to be a sort of dummy commit on this repo to trigger the image build or the builds should be set to trigger on update of the ampache repo.

**Comment by lachlan-00** [comment]
I'll do that now but will also be doing another release soon as well and will make sure to update the readme or something to kick the build

**Comment by TimoHocker** [comment]
Thanks for the quick help, everything is running up to date now

**Comment by lachlan-00** [comment]
I'll update the release procedure to include updating the docker repo.
