### ISSUE TITLE
Error while runing in raspberry pi 4

### ISSUE THREAD

**Issue by Javieraeros** [ampache/ampache-docker#33]
Hello!
I'm getting this error message when trying to run the docker image in my raspberry pi 4

`standard_init_linux.go:207: exec user process caused "exec format error"`

Raspbian buster

Linux raspberrypi 4.19.86-v7l+ #1283 SMP Fri Nov 29 18:37:40 GMT 2019 armv7l

**Comment by lachlan-00** [comment]
seems like that might have something to do with windows carriage returns
https://github.com/Azure/iotedge/issues/1912

**Comment by lachlan-00** [comment]
I just got a pi4 so i'm able to test this out.

**Comment by logoff** [comment]
I think it is related with the different architecture. Trying to run a Go program compiled for x86 architecture on ARM throws this kind of error.

So this issue may be transformed into a feature request: prepare Docker images for ARM architectures.

**Comment by lachlan-00** [comment]
I need to work out what binary it's trying to run, i'll try building the image manually and see what i can see.

**Comment by lachlan-00** [comment]
looks like there aren't any ubuntu armhf ports for 18.04 either.
![image](https://user-images.githubusercontent.com/1305249/72030691-99eb9f00-32d5-11ea-917c-09237609e38f.png)

I think this means i need to make an arm specific image? that's going to have to go into my repo as i still can't access the official docker hub account.

**Comment by wagnered** [comment]
Does http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu/dists/bionic/main/binary-armhf/ provide what you need?  Not really familiar with debian/ubuntu packaging system but the release file indicates it's 18.04.

null

**Comment by lachlan-00** [comment]
I've done some testing and that error i got is from the raspbian version of docker. It looks like i have to rebuild an arm specific version of ampache-docker though.

It would be good if i could get into the org on hub to add the tag but for the moment i'll just add them from my repo into the readme after it's built

**Comment by Javieraeros** [comment]
Thank you all for your comments!
I have ended to download repo and build the image myself in my pi4 and now works like a charm :smile:

**Comment by lachlan-00** [comment]
I'll be adding an image up for you (and now me) for the pi as soon as possible.

that way others can make use of it without having to run manually.

**Comment by lachlan-00** [comment]
Builds up! I've built on my docker server and tested on my personal pi4
You can pull from my personal docker account now. I'm building images for develop now.

Once /issues/27 is resolved i'll be able to manage the images from the official repo as well
```
docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 80:80 lachlan00/ampache
```
![image](https://user-images.githubusercontent.com/1305249/72114855-a680fd80-3390-11ea-9c70-45c54be43979.png)

I'll close this one and will update the readme to direct non-amd64 users
