### ISSUE TITLE
Different type of permission denied

### ISSUE THREAD

**Issue by awgcooper** [ampache/ampache-docker#34]
I've just setup image ID 5225e696553f. It all went smoothly until I was directed to the login page where I was presented with the dreaded:

ACCESS DENIED
You have been redirected to this page because you do not have access to this function
If you believe this is an error please contact an Ampache administrator
This event has been logged

I was using Caddy as the reverse, also tried nginx, neither of their logs revealed anything. I'm aware this has come up before but it didn't appear to me that a definitive caused was identified previously. Any advice would be very welcome.

**Comment by kuzi-moto** [comment]
Can you enable level 5 debugging and check Ampache logs?

**Comment by kuzi-moto** [comment]
Hey @awgcooper, it's been almost a year. Did you still want help on this?

**Comment by awgcooper** [comment]
Apologies, I just saw your response. No it's fine, I using a different solution now. Thanks anyway!
