### ISSUE TITLE
Corruption error

### ISSUE THREAD

**Issue by danai97** [ampache/ampache-docker#35]
Installed the docker container following the instruction, when I arrive at step 2 I press write for "config/ampache.cfg.php", it goes automatically to step 3, I wrote down username, password and second time password, but when I move on from that page the browser tells me that there is a corruption in the website data transmitted and to contact the website owner...
Sorry for my English but it's not my first language

**Comment by lachlan-00** [comment]
Some pictures might help.

I just installed new images to test and it seems okay.

**Comment by danai97** [comment]
I just tried to install the docker again to provide you some screenshot and this time it worked out of the box :/

I don't know why, because I did the exactly same thing...
I'll put the screenshots here even if now it works, maybe they can be useful to someone else

![Istantanea_2020-01-30_09-09-51](https://user-images.githubusercontent.com/43675739/73431773-79958a00-4341-11ea-9f4b-d3ed5132e6ed.png)
![Istantanea_2020-01-30_09-10-10](https://user-images.githubusercontent.com/43675739/73431774-79958a00-4341-11ea-8915-0ea8596bc3cb.png)
![Istantanea_2020-01-30_09-10-25](https://user-images.githubusercontent.com/43675739/73431778-7a2e2080-4341-11ea-90df-93cad2ed3ffe.png)
![Istantanea_2020-01-30_09-10-51](https://user-images.githubusercontent.com/43675739/73431780-7a2e2080-4341-11ea-98f9-74ca2c8447f6.png)
![Istantanea_2020-01-30_09-13-43](https://user-images.githubusercontent.com/43675739/73431781-7a2e2080-4341-11ea-962a-b6c255b1fb86.png)
![Istantanea_2020-01-30_09-13-56](https://user-images.githubusercontent.com/43675739/73431782-7ac6b700-4341-11ea-9be6-a05cc1d25f05.png)
![Istantanea_2020-01-30_09-14-05](https://user-images.githubusercontent.com/43675739/73431783-7ac6b700-4341-11ea-91db-596f6d80646f.png)
![Istantanea_2020-01-30_09-14-28](https://user-images.githubusercontent.com/43675739/73431785-7ac6b700-4341-11ea-9e43-16672e51f869.png)
![Istantanea_2020-01-30_09-17-48](https://user-images.githubusercontent.com/43675739/73431786-7b5f4d80-4341-11ea-8c19-40e357226425.png)

**Comment by lachlan-00** [comment]
I rebuilt the images for develop while looking at this so you also helped with that.

it's good to know that it worked out.
