### ISSUE TITLE
a working docker-compose.yml and standard ampache/ampache image

### ISSUE THREAD

**Issue by adamshand** [ampache/ampache-docker#38]
Hello,

I've built a working docker-compose.yml for ampache/ampache:latest which has persistent storage for mysql and configuration files.

It's pretty rough, at the "it works for me" stage.  Please take anything that's of use.

https://github.com/adamshand/homelan/tree/master/ampache

Cheers,
Adam.

**Comment by lachlan-00** [comment]
@kuzi-moto can you merge into your work?

**Comment by kuzi-moto** [comment]
Sure thing. I'll double-check everything and see what improvements I can make.

**Comment by lachlan-00** [comment]
This is in the repo now, a new ampache release is impending too.
