### ISSUE TITLE
.git folder is reachable via web browser (tag: develop)

### ISSUE THREAD

**Issue by BLeeEZ** [ampache/ampache-docker#40]
## Description

The `.git` folder is reachable via web browser: https://ampache.mydomain.com/.git/config
Tested with the docker hub image ampache/ampache:develop
This only occurs on tag `develop`. On tag `latest` the `.git` folder is removed on step 16 in the Dockerfile.

## Possible fixes

- Place the `.git` folder outside `/var/www` via `-git-dir` and `--work--tree`
- Adjust the root .htaccess file in ampache/ampache

**Comment by lachlan-00** [comment]
need to update the apache conf to deny that

this should cover it.
```
<Directorymatch "^/.*/\.git/">
  Order deny,allow
  Deny from all
</Directorymatch>
```

**Comment by BLeeEZ** [comment]
It is fixed. Could you please update the docker hub image `ampache/ampache` as well. This would make the changes easier available. Thank you.

**Comment by kuzi-moto** [comment]
@BLeeEZ I'm working on a big update to the image, so I will make sure to include this.

**Comment by BLeeEZ** [comment]
@kuzi-moto OK cool. I am looking forward to play with it.
