### ISSUE TITLE
ERROR: Waiting for confirmation of MySQL service startup 

### ISSUE THREAD

**Issue by pietrotti97** [ampache/ampache-docker#41]
Hi, 
I'm trying to run the official ampache/ampache docker image on a raspberrypi.
Docker is already running and working fine for other containers.
The syntax I used is:  `docker run --name=ampache -d -v /mypath:/media:ro -p 50:80 ampache/ampache:develop`
The log I got with `docker logs -f ampache` is: 
=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql
=> Installing MySQL ...
=> Done!
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
and continues forever.

**Comment by lachlan-00** [comment]
i'll run up a build and see what happens. the structure hasn't changed so i'm not sure why that happened

**Comment by lachlan-00** [comment]
i ran a fresh image on port 80:80 and 50:80 and got to install with develop
![image](https://user-images.githubusercontent.com/1305249/89589951-2cfbb000-d88a-11ea-962b-3951f9f4fc78.png)

can you verify against the digest hash i have?
![image](https://user-images.githubusercontent.com/1305249/89590251-c32fd600-d88a-11ea-96e6-7c1edd2e2c3e.png)

```sha256:ef3daa05c1f29c0a522d2e5c6f36494e3b4e191a30b1cbd1f7eca7138f945701```

**Comment by pietrotti97** [comment]
Yes, the digest is correct. 
Upon further inspection, seems like there is a problem with mysql not finding the socket.

**Comment by pietrotti97** [comment]
No idea on what happened. 
I updated my system along with docker, and now it's working fine. 

Thankyou
