### ISSUE TITLE
"ampache.cfg.php.dist" is not readable

### ISSUE THREAD

**Issue by YasserAntonio** [ampache/ampache-docker#45]
I'm using the ampache/ampache:nosql image on armv7 when I try to install ampache
 I get the error ( screenshot) that "ampache.cfg.php.dist"is  not readable.

<img width="797" alt="Capture d’écran 2020-09-02 à 17 44 00" src="https://user-images.githubusercontent.com/8104486/92005548-e9d71480-ed43-11ea-963d-bd186cc43e9c.png">

 I chmoded it to 777:
```bash
root@b6d4084a3b20:/# chmod 777 /var/temp/ampache.cfg.php.dist
root@b6d4084a3b20:/# ls -la /var/temp/ampache.cfg.php.dist
-rwxrwxrwx 1 www-data www-data 41850 Aug 20 02:56 /var/temp/ampache.cfg.php.dist
root@b6d4084a3b20:/# 
```

but I'm still getting the error. Any idea how to solve this ?

**Comment by wagnered** [comment]
Does the Apache2 access.log give any clue?

**Comment by YasserAntonio** [comment]
Very weird, I restarted the service and now it passed the test but I went to the end  and the web app only load html without any content : 
<img width="1010" alt="Capture d’écran 2020-09-02 à 18 08 33" src="https://user-images.githubusercontent.com/8104486/92008476-84852280-ed47-11ea-903f-e8a917c289c7.png">

**Comment by YasserAntonio** [comment]
> Does the Apache2 access.log give any clue?

nope it's empty

**Comment by YasserAntonio** [comment]
okey I got it the I click on a link it add 2 times the hostname, exemple : http://ampache.lnampache.ln/index.php  , I will reconfigure it without specifying hostname this time.

**Comment by YasserAntonio** [comment]
Got the previous error again... damn 
<img width="746" alt="Capture d’écran 2020-09-02 à 18 20 03" src="https://user-images.githubusercontent.com/8104486/92009523-f14cec80-ed48-11ea-9f0a-90fce5d1ebf0.png">

**Comment by YasserAntonio** [comment]
I checked the logs in var/logs and found nothing. Any idea where I can find the result of the test from the installation test ?

**Comment by YasserAntonio** [comment]
had to remove my docker volume : - /home/pi/ampache/config:/var/www/config
so no persistant configuration for the moment... ig you guys no a way to make it persistant I will be very interested

**Comment by wagnered** [comment]
Sorry, I'm not very familiar with docker so I'll leave this for @lachlan-00.

**Comment by YasserAntonio** [comment]
no problem ! Thanks for you help !
