### ISSUE TITLE
todo; add inotifywait.sh

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache-docker#49]
inotifywait.sh using update_file.inc allows clean, add, verify, gather to run automatically on media folders so i'll add that to the images.

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/blob/develop/docs/examples/inotifywait.sh

**Comment by lachlan-00** [comment]
i'm pretty happy with this example the updates on single file are pretty good.

**Comment by lachlan-00** [comment]
... needs to be in the repo though.

**Comment by xeruf** [comment]
While we are at it, any reason all these .sh-scripts are in the repo root? Seems they would belong in a subdirectory as they are only used during the setup and not to be invoked manually.

**Comment by lachlan-00** [comment]
that's just the way it was forked over years ago.

when i update the phpversion i'll move things around again to match the other docker repos/paths that i've got going

**Comment by lachlan-00** [comment]
added, moved and building now
