### ISSUE TITLE
WSL2 installation issues - missing files/bad permissions/database access denied

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [ampache/ampache-docker#51]
I'm having issues installing it under WSL2. 

I have multiple containers (mostly linuxserver.io ones) in a docker-compose.yml file. The rest of them have their own user/group configured with the PUID/PGID environment variables, which I would like to be able to do for ampache as well. 

The ampache section is:
````
ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
        - 8081:80
    volumes:
        - /home/adrian/docker/config/ampache/config:/var/www/config
        - /home/adrian/docker/config/ampache/log:/var/log/ampache
        - /home/adrian/docker/data/media/music:/media
        - /home/adrian/docker/config/ampache/mysql:/var/lib/mysql
        - /home/adrian/docker/config/ampache/sites-enabled:/etc/apache2/sites-enabled
````

1. When starting up, it looks like the `ln -s /etc/apache2/sites-available/001-ampache.conf /etc/apache2/sites-enabled/` command in the Dockerfile doesn't work, as `/etc/apache2/sites-enabled` is empty. Running it manually afterwards from within the container as root gets it to work.

2. ampache.cfg.php doesn't get copied/moved at all. I ran `mv /var/temp/ampache.cfg.php.dist /var/www/config/ampache.cfg.php.dist` manually to get that to show up. 

3. Then when attempting to run through the install, putting in `admin` and the supplied password doesn't seem to work - 
`Unable to connect to the database: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES)`

I've tried several combinations of removing the container, changing permissions, putting files in manually, etc, but I still can't get it working. 
 
````
=> An empty or uninitialized MySQL volume is detected in
=> Installing MySQL ...
Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
OK
To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system
PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:
'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h 90497b6cf52c password 'new-password'
Alternatively you can run:
'/usr/bin/mysql_secure_installation'
which will also give you the option of removing the test
databases and anonymous user created by default. This is
strongly recommended for production servers.
See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.
You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql'
You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl
Please report any problems at http://mariadb.org/jira
The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/
=> Done!
201025 08:14:05 mysqld_safe Logging to syslog.
201025 08:14:05 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
=> Waiting for confirmation of MySQL service startup
=> Creating MySQL admin user with random password
=> Done!
========================================================================
You can now connect to this MySQL Server using:
mysql -uadmin -ptO6iaaL08Bip -h<host> -P<port>
Please remember to change the above password as soon as possible!
MySQL user 'root' has no password but only allows local connections
========================================================================
2020-10-25 08:14:18,483 INFO Set uid to user 0 succeeded
2020-10-25 08:14:18,486 INFO supervisord started with pid 1
2020-10-25 08:14:19,488 INFO spawned: 'cron' with pid 233
2020-10-25 08:14:19,489 INFO spawned: 'inotifywatch' with pid 234
2020-10-25 08:14:19,490 INFO spawned: 'mysql' with pid 235
2020-10-25 08:14:19,490 INFO spawned: 'apache2' with pid 236
2020-10-25 08:14:20,552 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-25 08:14:20,552 INFO success: inotifywatch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-25 08:14:20,552 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-25 08:14:20,552 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
````

**Comment by lachlan-00** [comment]
docker from wsl2 or can it run from the Windows docker?

the log looks like it's running. do the ports in wsl2 have any restrictions?

**Comment by kuzi-moto** [comment]
> 1. When starting up, it looks like the ln -s /etc/apache2/sites-available/001-ampache.conf /etc/apache2/sites-enabled/ command in the Dockerfile doesn't work, as /etc/apache2/sites-enabled is empty. Running it manually afterwards from within the container as root gets it to work.

Dockerfile commands are run when building the image. According to the [Docker documentation](https://docs.docker.com/storage/bind-mounts/#mount-into-a-non-empty-directory-on-the-container): "If you bind-mount into a non-empty directory on the container, the directory’s existing contents are obscured by the bind mount". So if your bind mount is empty, so will the directory in the container. That directory was not intended to be bind-mounted so the contents are not re-copied over when missing when the container starts. Best solution around this would be to start the container with an anonymous volume at that mount point, and copy the contents into the directory of your choice.

I've been meaning to fix that issue, but haven't had the time yet.

> 2. ampache.cfg.php doesn't get copied/moved at all. I ran mv /var/temp/ampache.cfg.php.dist /var/www/config/ampache.cfg.php.dist manually to get that to show up.

Same issue as above.

> 3. Then when attempting to run through the install, putting in admin and the supplied password doesn't seem to work -
    Unable to connect to the database: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES)

Hmm, I'm not sure about this one. I've had some issues with it but last time I tried it was working... Can you also try the user `root` with no password?

**Comment by lachlan-00** [comment]
i didn't even know docker on windows had support for wsl2 but i'm installing now to check it out

**Comment by kuzi-moto** [comment]
Yeah, it's very neat. With Visual Studio Code managing Docker and code is incredibly easy with its remoting capabilities.

I was doing some research, and according to the [Docker documentation](https://docs.docker.com/storage/volumes/) "volumes are the preferred mechanism for persisting data generated by and used by Docker containers."

Definitely seems like volumes typically work a lot better than bind-mounts, but if it only takes a minute to fix the current issues we might as well.

**Comment by Adrian-Rasmussen** [comment]
> Best solution around this would be to start the container with an anonymous volume at that mount point, and copy the contents into the directory of your choice.

I've changed them to be anonymous volumes

> Hmm, I'm not sure about this one. I've had some issues with it but last time I tried it was working... Can you also try the user `root` with no password?

I had tried beforehand and it didn't work, but now with the anonymous volumes it allows me to progress

Seems to all be working now after that, thanks.
