### ISSUE TITLE
Database access denied

### ISSUE THREAD

**Issue by aguinaldoabbj** [ampache/ampache-docker#53]
Hi all,
I'm running ampache-docker on GCP, with COS. I can run ampache-docker, everithing shows up fine but when I run the configuration wizard, in Step 1 - Create the Ampache database, I cannot connect to the database.
`Unable to connect to the database: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES)
`
I'm using user admin and the password shown in the container logs. If I exec into the container, I can reproduce the problem with `mysql -uadmin -ppassword`

**Comment by aguinaldoabbj** [comment]
I've seen PR #50 already contemplates this issue. When is it going to be merged?

**Comment by ralcaidev** [comment]
Also faced this problem. Just use root without password. As Mariadb log says:

> MySQL user 'root' has no password but only allows local connections

**Comment by lachlan-00** [comment]
i just noticed that the password isn't being set

**Comment by lachlan-00** [comment]
merged the admin change now and will update the other images
