### ISSUE TITLE
release archives

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache-docker#55]
hey @kuzi-moto if i change the release archive to use the master release file we won't need to add composer at all.

do you have an issue with that?

**Comment by lachlan-00** [comment]
aww yeah, that cut it down by almost half
![image](https://user-images.githubusercontent.com/1305249/100438431-dc84b880-30ed-11eb-8373-7058ac0709a0.png)

**Comment by kuzi-moto** [comment]
Yeah seems to make a lot more sense this way.

**Comment by lachlan-00** [comment]
I've been researching the multi architecture images and they're still a pain. I think I'll just Cron a develop build every fortnight. It might be easier to automate a develop preview as well

**Comment by kuzi-moto** [comment]
There should be a way to schedule builds every commit to the develop branch. Something I was trying to look into.

**Comment by lachlan-00** [comment]
There are automated builds for the repo but I had to disable them after starting arm builds.

**Comment by kuzi-moto** [comment]
They would just update on a push to the Docker repo though, right? And not to the main Ampache project.

I wanted to look at automating multi arch builds, maybe there's an easy fix.

**Comment by lachlan-00** [comment]
Yeah the old waywas to just bump the docker readme to force a push.

To do more than amd64 requires some kind of compose magic I don't understand
