### ISSUE TITLE
Does not install the latest stable version

### ISSUE THREAD

**Issue by arielelkin** [ampache/ampache-docker#6]
This currently installs Ampache v3.8.1, not v3.8.2

**Comment by evil666** [comment]
I have no clue why it installs an older version. I took a look at the docker file and just started to copy and past the commands one at a time to grab the latest master, copy the contents to /var/www, changed permissions, ran  composer install and restarted Apache. Prompted for the database upgrades and then all was good. Something just isn't working right upon the first pull of this docker image.

**Comment by evil666** [comment]
Docker file is incorrect or out of date when it comes to the current master file.

Docker file says:
# For local testing / faster builds
# COPY master.tar.gz /opt/master.tar.gz
ADD https://github.com/ampache/ampache/archive/master.tar.gz /opt/master.tar.gz

and it needs to be:
# For local testing / faster builds
# COPY master.tar.gz /opt/master.tar.gz
ADD https://github.com/ampache/ampache/archive/ampache-master.tar.gz /opt/ampache-master.tar.gz

**Comment by arielelkin** [comment]
@evil666 sounds good, could you please make a pull request?

**Comment by mrbills** [comment]
question - (I'm a docker newb) 
Is there a way to manually update to 3.8.2 somehow?  Some sort of clever apt-get command that just operates on the existing container?  Or do you need to create a whole new docker image once these commands are updated?  I'd hate to have to setup config, prefs and playlists again.

**Comment by arielelkin** [comment]
@mrbills you should do the following:

1. go inside your ampache container: `docker exec -ti name_of_ampache_container bash`
1. follow the instructions here: https://github.com/ampache/ampache/wiki/Upgrade

**Comment by arielelkin** [comment]
fixed via https://github.com/ampache/ampache-docker/pull/7
