### ISSUE TITLE
Container doesn't start

### ISSUE THREAD

**Issue by grisumaniac** [ampache/ampache-docker#63]
After trying to start the new Container (4.4.3:nosql) i'm getting following error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.`

**Comment by lachlan-00** [comment]
will check now

**Comment by lachlan-00** [comment]
the file isn't executable so it's there but not able to execute
rebuilding now

**Comment by lachlan-00** [comment]
working on the new build and added to all the other branches too to make sure it gets set at build time
https://hub.docker.com/layers/ampache/ampache/nosql/images
/sha256-9db0c8d20b50a9ffa42858de2aa9a455c90f9a415a50fc2f6f9b1f46fc7aaf43?context=repo
