### ISSUE TITLE
LDAP login support not functional in Docker container

### ISSUE THREAD

**Issue by WilliamBolhofer** [ampache/ampache-docker#66]
The Docker container does not support LDAP login in its current state because the PHP 'ldap_connect()' function does not exist. Adding the "php-ldap" package to the apt-get line of the Dockerfile will fix this.

**Comment by lachlan-00** [comment]
i'll add it now and do a develop build

**Comment by lachlan-00** [comment]
then i'll add some master ones and close this off after that

**Comment by WilliamBolhofer** [comment]
I just got the latest image from Docker Hub and the issue seems resolved. LDAP works as expected now. Thanks!
