### ISSUE TITLE
Cover art is super low resolution

### ISSUE THREAD

**Issue by pablojrl123** [ampache/ampache-docker#68]
The automatically downloaded cover art, by using the 'Gather All Art' button at the catalog admin options, is super low resolution. And I do mean, super low. This issue occurs with both the stable and develop branch. I have not made any configuration changes, it is using the default configuration of the docker image. If I upload the cover art manually, then it looks fine.

Samples:
![image](https://user-images.githubusercontent.com/41169964/128790305-f89c5eb5-5fe0-45f6-8e1b-96c5bbcd4068.png)
![image](https://user-images.githubusercontent.com/41169964/128790335-ae41df48-8c11-4870-afa5-f39d32ca7263.png)

**Comment by lachlan-00** [comment]
if you have local files (like folder.jpg) you might want to set minimum resolution for art
![image](https://user-images.githubusercontent.com/1305249/128810767-3f5ee952-18d0-4f99-9f3c-43caa7c5dd93.png)

online sources that cover most things are spotify and the audiodb
https://developer.spotify.com/dashboard/
https://www.theaudiodb.com/ (audiodb requires a patreon sub for art)

for spotify the api data is set in the config file too
for audiodb it's in the interface
`preferences.php?action=admin&tab=plugins`

**Comment by pablojrl123** [comment]
> 
> 
> if you have local files (like folder.jpg) you might want to set minimum resolution for art
> ![image](https://user-images.githubusercontent.com/1305249/128810767-3f5ee952-18d0-4f99-9f3c-43caa7c5dd93.png)
> 
> online sources that cover most things are spotify and the audiodb
> https://developer.spotify.com/dashboard/
> https://www.theaudiodb.com/ (audiodb requires a patreon sub for art)
> 
> for spotify the api data is set in the config file too
> for audiodb it's in the interface
> `preferences.php?action=admin&tab=plugins`

Thank you, using the Spotify DB worked out nicely for most albums. I guess I should've read the docs better. And just to know, from where was it downloading those low res cover art before?

**Comment by lachlan-00** [comment]
it actually depends on the source that ampache finds. i don't really have an easy answer on that but the short answer is that online sources (in general) are hacked or require payment to access art these days.

Spotify is the best relatively 'free' access but still requires custom setup.

**Comment by lachlan-00** [comment]
glad it works though
