### ISSUE TITLE
Upgrade to Ampache 5 broke my Database connection

### ISSUE THREAD

**Issue by throny** [ampache/ampache-docker#70]
Hello, 

I just realized that watchtowerr updated the image of my ampache setup.
I thought its a straight forward update process like usual, somehow this time it wasn't the case.

It was pretty easy to adjust the new path for the public dir, however my database is not running correctly anymore.
The updater throws a database connection error. 
After recreating with docker-compose this is the log output:

```
=> Using an existing volume of MySQL
2021-09-04 12:44:05,656 INFO Set uid to user 0 succeeded
2021-09-04 12:44:05,659 INFO supervisord started with pid 1
2021-09-04 12:44:06,660 INFO spawned: 'apache2' with pid 8
2021-09-04 12:44:06,662 INFO spawned: 'cron' with pid 9
2021-09-04 12:44:06,663 INFO spawned: 'inotifywatch' with pid 10
2021-09-04 12:44:06,665 INFO spawned: 'mysql' with pid 11
2021-09-04 12:44:07,762 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-04 12:44:07,762 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-04 12:44:07,763 INFO success: inotifywatch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-04 12:44:07,763 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-09-04 12:44:07,763 INFO exited: mysql (exit status 0; expected)
```

I wouldn't consider it as "expected", however I have no clue what to do in this case. Any ideas?

**Comment by kuzi-moto** [comment]
Can you post your docker-compose file?

**Comment by throny** [comment]
Sure thing.

```
version : '2.1'

services:
  ampache:
    container_name: ampache
    restart: unless-stopped
    image: ampache/ampache:latest
    ports:
      - 80
      - 443
    volumes:
      - /data/music:/media:ro
      - ${PWD}/mysql:/var/lib/mysql
      - ${PWD}/conf/ampache:/var/www/config
      - ${PWD}/conf/apache:/etc/apache2/sites-enabled
      - ${PWD}/logs:/var/log/ampache
    environment:
      - VIRTUAL_HOST=hostname.tld
      - LETSENCRYPT_HOST=hostname.tld
    networks:
      proxy:
networks:
  proxy:
    external:
      name: https-proxy
```
I am running Ampache behind an nginx reverse proxy (the jwilder one)

**Comment by kuzi-moto** [comment]
Probably need to change `- ${PWD}/conf/ampache:/var/www/config` to `- ${PWD}/conf/ampache:/var/www/public/config`

**Comment by throny** [comment]
So the config folder moved to the public subdirectory? Weird.
After changing it just redirects me to the install page which does not look right.

**Comment by kuzi-moto** [comment]
Yeah my bad, not sure what I was thinking. With Ampache 5 the web content was moved to the `/public` subdirectory, but that didn't affect the config directory.

It's probably the file here `- ${PWD}/conf/apache:/etc/apache2/sites-enabled` which needs to be edited to serve the site from the public directory.

**Comment by lachlan-00** [comment]
sorry! will fix up compose tomorrow

**Comment by throny** [comment]
> It's probably the file here `- ${PWD}/conf/apache:/etc/apache2/sites-enabled` which needs to be edited to serve the site from the public directory.
Yeah, thats where I adjusted the path to access it again but it's not a webserver thing as the database is just not running as you can see in the docker log.




> sorry! will fix up compose tomorrow

thank you! whats the issue tho? I dont really understand yet

**Comment by lachlan-00** [comment]
just looked, i thought the compose file needed something.

your site config for apache needs to reference the public folder. does it match the repo files?
```
DocumentRoot /var/www/public/

# deny access to the .git folder
<Directorymatch "^/.*/\.git/">
  Order deny,allow
  Deny from all
</Directorymatch>

<Directory /var/www/public/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all

    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</Directory>
```

**Comment by throny** [comment]
As I mentioned above, the apache config is not my problem as I already changed the DocumentRoot and the Directory but the mysql database is. It just exits with status 0 as you can see in my first comment (fresh created container with exact the same apache config @lachlan-00 posted above)

**Comment by danielfomin96** [comment]
I had the same problem. I tried to start mysqld from within the container myself and saw that the error 'Unknown table engine innodb' was thrown. The solution for me was to delete the `ib_logfile` files in /var/lib/mysql within the container. Now I could update ampache again.

**Comment by throny** [comment]
You're my man, @danielfomin96 ! Thank you for pointing  out. Worked well :)
