### ISSUE TITLE
DISCOURSE_SMTP_PASSWORD: Special characters are truncated

### ISSUE THREAD

**Issue by jensensen** [ampache/ampache-docker#73]
The password that was set in docker-compose.yml is not the same as it should be in:
/opt/bitnami/discourse/config/discourse.conf

Special characters are truncated

I've installed Discourse, but email doesn’t seem to work. My setup is based on

image: docker.io/bitnami/discourse:2
and 
https://github.com/ampache/ampache-docker/blob/master/docker-compose.yml

**Comment by kuzi-moto** [comment]
I think you're in the wrong place. This is for the media software Ampache. I don't believe our docker-compose file should be used for any other software.

**Comment by jensensen** [comment]
OMG, yes, you are right!
Please excuse me. And please close/delete this issue.
Thank you!
