### ISSUE TITLE
Ampache config.php is overwritten

### ISSUE THREAD

**Issue by manuelfonseca71** [ampache/ampache-docker#80]
Not sure if this has been reported yet, or what I might be doing wrong...
I'm currently using ampache/ampache:nosql docker image.

which appears to include the following lines within the run.sh
Copy Ampache config .dist files
cp /var/tmp/* /var/www/config/

This overwrites the ampache existing configurations with the default ones within the /var/tmp, making the system unusable.

Am I doing something wrong, or using an image that should not be used?

Thank you for your help,

**Comment by kuzi-moto** [comment]
This was my bad, sorry! We were working on getting it fixed. Should be for the standard image, but not on Develop or nosql.

**Comment by manuelfonseca71** [comment]
Ah... Thanks for the quick reply.

The first time it got me unaware, but it was a quick fix.

Oh well, it is reported then and at least you are now aware.

Thanks again
Mnl

A segunda, 15/11/2021, 21:57, Kuzma Fesenko ***@***.***>
escreveu:

**Comment by lachlan-00** [comment]
i didn't update the branches on sat i've updated them all now.

**Comment by manuelfonseca71** [comment]
Image updated overnight and I can confirm that it no longer overwrites the existing active configuration.

Thank you,
Mnl
