### ISSUE TITLE
ampache docker images stuck to hard coded 5.3.0 version ?

### ISSUE THREAD

**Issue by alxrdn** [ampache/ampache-docker#83]
hi

it looks like the images pushed to hub.docker.com are stuck to 5.3.0 albeit their tags; for instance:
[ampache/ampache:5.3.2](https://hub.docker.com/layers/ampache/ampache/ampache/5.3.2/images/sha256-213ac48c2400eb9b31dcdb0530f7ff9f1ea2a200a5a24b7a02d964d5a16a2720?context=explore)

because of hard coded version in [Docker file](https://github.com/ampache/ampache-docker/blob/master/Dockerfile#L6) ?

**Comment by aguinaldoabbj** [comment]
> hi
> 
> it looks like the images pushed to hub.docker.com are stuck to 5.3.0 albeit their tags; for instance: [ampache/ampache:5.3.2](https://hub.docker.com/layers/ampache/ampache/ampache/5.3.2/images/sha256-213ac48c2400eb9b31dcdb0530f7ff9f1ea2a200a5a24b7a02d964d5a16a2720?context=explore)
> 
> because of hard coded version in [Docker file](https://github.com/ampache/ampache-docker/blob/master/Dockerfile#L6) ?

I was just about to fill an issue regarding this very same problem.

**Comment by lachlan-00** [comment]
updated today. all good now.
