### ISSUE TITLE
locales packages and setting missing from Docker images

### ISSUE THREAD

**Issue by landure** [ampache/ampache-docker#85]
The docker image is missing UTF-8 locales resulting in a folder named `'Édith Piaf'` to be listed as `''$'\303\211''dith Piaf'`.

Proposed solution:

add `locales` package to Docker image.

**Comment by landure** [comment]
Additionnaly, /etc/locale.gen needs to be edited and en_US.UTF-8 uncommented.

**Comment by lachlan-00** [comment]
i've rebuilt all the images with locales and sed in us utf8

**Comment by landure** [comment]
It works perfectly. Thank you.
