### ISSUE TITLE
Latest docker image error

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache-docker#90]
Did a docker-pull to the latest docker image (digest d859c54589ce).  Now I get a blank screen after the database upgrades.

In an incognito browsing session, I went to the login screen, here's the log that printed:
```
2022-09-08T08:15:31-05:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Login\DefaultAction" for action "default"
2022-09-08T08:15:31-05:00 [ampache] (Ampache\Module\System\Session) -> Unable to read value from key bfabj2civpudh54cd9fv8sc7b6 no data found
2022-09-08T08:15:31-05:00 [ampache] (/var/www/src/Module/System/Core.php:143) -> filter_has_var(): Argument #1 ($input_type) must be of type int, string given
2022-09-08T08:15:31-05:00 [ampache] (Ampache\Module\System\Session) -> Writing to bfabj2civpudh54cd9fv8sc7b6 with expiration 1662646531
```

**Comment by troycarpenter** [comment]
I am not getting this on my stand-alone test machine which is up to date with the develop branch.

**Comment by troycarpenter** [comment]
So the quick fix was to comment out lines 142 through 145 in src/Module/System/Core.php.  Since I am using a proxy, I just simply returned the value for HTTP_X_FORWARDED_FOR variable.

The problem is this statement:
 filter_has_var($_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP)

**Comment by troycarpenter** [comment]
I think this is a problem in the source, not with the docker image itself.

**Comment by shikasta-net** [comment]
I can confirm this issue.  I'll try your fix. It's probably an unfortunate combination of PHP8 update and the source, and proxies.

**Comment by shikasta-net** [comment]
Yup, unborked by doing the following:
replace `filter_has_var($_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP)` with `filter_var($_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP)`.
The function `filter_has_var` is the wrong function in this case, but the `&&` means this bug only occurs if the header is set; i.e., using a proxy.

**Comment by troycarpenter** [comment]
Due to other problems I'm having with this image (LDAP issues with some users), I'm not able to try the filter_var change to see if that's what the change should be.

**Comment by troycarpenter** [comment]
I see you made the fix.  I'm trusting the function change is the root.  Focusing on the LDAP problem that has crept up.  Seems one of my LDAP users (me, specifically) stopped working about three DOCKER images ago when trying to log in via the Subsonic API.  So far I've seen other users log in via their mobile apps, so it may be that my password has newly blocked characters.
