### ISSUE TITLE
Latest version not available in dockerhub

### ISSUE THREAD

**Issue by aguinaldoabbj** [ampache/ampache-docker#93]
Dear,

The latest version of Ampache (5.5.3) is still not available in a container image on docker hub. The latest vesion available there is 5.5.2.

Is there something wrong with the build pipeline?

**Comment by lachlan-00** [comment]
there sure is! i didn't notice it as i just run the builds in the background
![image](https://user-images.githubusercontent.com/1305249/198902122-3fd39bd4-7b3b-48ae-805b-cc135029004d.png)

**Comment by lachlan-00** [comment]
found it. my version string was reading from the next version. i'll fix that so if the zip isn't available it willask me to input the string again

**Comment by aguinaldoabbj** [comment]
Dear, the image tagged as the latest is still the one built 2 months ago.

**Comment by lachlan-00** [comment]
> Dear, the image tagged as the latest is still the one built 2 months ago.

all there for latest now. i'm rebuilding nosql again too
