### ISSUE TITLE
Is FFMPEG Transcoding available via the :latest Docker image?

### ISSUE THREAD

**Issue by DroWnThePoor** [ampache/ampache-docker#99]
I don't see anything indicating whether this is included/working or not, but I enabled it during the setup process. 
Does the Ampache image have FFMPEG included, or would I have to modify my docker-compose to access it on the OS where Docker is installed? 
Maybe this should be indicated on the Docker Hub README for future reference.
I have Allow Transcoding set to Default in the Admin options.
I've connected via DSub app for Android, and I noticed a sort of low-resolution playback of several albums from my catalog while others play with the expected clarity.
The songs with the lower resolution also seem to start playing with a longer delay followed by a choppy couple of seconds almost like buffering.
Is this be caused by transcoding or a lack of transcoding?

**Comment by lachlan-00** [comment]
it's installed as part of the dockerfile so you don't need to add anymore. https://github.com/ampache/ampache-docker/blob/d1ec6534ef1cab88aabac6e64dd179f52844ea8d/Dockerfile#L24

make sure all the transcoding options are enabled as well.
https://github.com/ampache/ampache/wiki/Transcoding

I'm not sure about any performance issues like that but if you enable logging it will tell you moe about the stream action and what happens

**Comment by DroWnThePoor** [comment]
Thank you. I'll close this since I was mainly trying to find out if it was or wasn't installed.
